### ISSUE TITLE
amazonlinux:latest = Amazon Linux 2 - yum-cron no likey

### ISSUE THREAD

**Issue by Zordrak** [bonusbits/bonusbits_base#9]
yum-cron, and possibly other cookbooks, can't handle EL7 (systemd replacing SysV init)

FROM amazonlinux:latest has for some time pulled the latest Amazon Linux 2 image.

To make this structure work, you have to change it to FROM amazonlinux:2018.03.

That said, my next job is to make this structure fit around Amazon Linux 2 as that's what we'll be using.

**Comment by Zordrak** [comment]
#10

**Comment by LevonBecker** [comment]
Removed in v3.0.0 that I'm about ready to cut... Also, as a note, there was an attribute you could override to not setup yum-cron. Also, v3.0.0 now locks amzn1 & 2 versions and will work with both.
